ur3_arm:
  # kinematics_solver: ur_kinematics/UR3KinematicsPlugin
  # kinematics_solver: ur3_ext_ee_kinematics/IKFastKinematicsPlugin
  # kinematics_solver: ur3_arm_kinematics/IKFastKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
